### ISSUE TITLE
Balance Law solver checklist

### ISSUE THREAD

**Issue by jkozdon** [climate-machine/CLIMA#160]
- [x] source terms
- [x] constant auxiliary state
- [x] documentation
- [x] boundary conditions
- [x] gradient terms (pr #203)
- [x] GPUify
- [x] Tutorial style docs (like done with [JuAFEM.jl] (http://kristofferc.github.io/JuAFEM.jl/dev/examples/generated/heat_equation/) examples) (pr #191)
- [ ] compare performance with current dycore
- [ ] Better docs for tests
- [ ] Add `Float32` tests
- [ ] pinned memory and multiple GPU queues
- [ ] update interface to allow for separation of tracer/advected state and nonlinear terms
- [ ] IMEX interface

Tabled items:
- switch to skew formulation (as opposed to weak form)
  - This is something we will likely want to think about in the future, but not high priority right now
- dynamic auxiliary state
  - if needed, this would be better stored at the end of the solution vector and updated during the ODE update.
  - To do this will requiring modifying the `MPIStateArray` so that the norm is only performed over "real" states

**Comment by simonbyrne** [comment]
- [ ] documentation
